---
editor_options: 
  markdown: 
    wrap: 72
---

# FAQ {#sec-index}

```{=html}
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-2662B66TL7"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-2662B66TL7');
</script>
```

> **If you encounter any issues or have suggestions for new features,
> please submit a request on the [GitHub Issues
> page](https://github.com/TeddYenn/ShiNyP/issues) or email us
> at: [teddyhuangyh\@gmail.com](mailto:teddyhuangyh@gmail.com)**

## General Usage {.unnumbered}

1.  **Can I use the online version of *ShiNyP* platform?**

    Yes, a trial version of *ShiNyP* is available online at:
    <https://teddyhuang.shinyapps.io/ShiNyP_Demo/>

    This web-based DEMO is hosted on Shinyapps.io and is intended for
    trial purposes. Please note that, due to server memory limitations
    (1GB RAM), this version is not suitable for the analysis of
    large-scale SNP datasets. For complete functionality and to analyze
    larger datasets, we strongly recommend downloading *ShiNyP* from
    GitHub.

    For more information: [Get
    Started](https://teddyenn.github.io/ShiNyP-guide/get-started.html)

2.  **Do I need programming skills to use *ShiNyP*?**

    No programming experience is required. *ShiNyP* provides a
    user-friendly graphical interface that allows you to perform all
    analyses interactively without coding.

3.  **How to update/re-installl the *ShiNyP* platform?**

    Remove the existing version:

    ``` r
    detach("package:ShiNyP", unload = TRUE)
    remove.packages("ShiNyP")
    ```

    Re-install the latest version & load and run *ShiNyP*:

    ``` r
    install_github("TeddYenn/ShiNyP", force = TRUE)
    library(ShiNyP)
    ShiNyP::run_ShiNyP()
    ```

4.  **Is my data secure when using *ShiNyP*?**

    All analyses are conducted **locally** on your machine or server. No
    user data is transmitted to third-party servers unless you
    explicitly use AI features (*ShiNyP* *AI* chatbot and reporting
    system).

5.  **Does *ShiNyP* require internet access to function?**

    *ShiNyP* runs **locally** and does not require internet access for
    core analyses. Internet is only needed when installing the packages
    at first and using AI features (*ShiNyP* *AI* chatbot and reporting
    system).

------------------------------------------------------------------------

## Analysis & Features {.unnumbered}

1.  **What makes *ShiNyP* different from other SNP analysis tools?**

    *ShiNyP* uniquely integrates a modular Graphical User Interface
    (GUI), *ShiNyP AI* (real-time chatbot), cross-species compatibility,
    AI-based interpretation, customizable visualizations, and
    open-source accessibility—all in one platform, making it a versatile
    tool for researchers in genomics, breeding, and evolutionary
    biology.

2.  **What types of input data are supported by *ShiNyP*?**

    *ShiNyP* supports genome-wide biallelic SNP datasets in Variant Call
    Format (VCF). It is also compatible with `data.frame` and `genlight`
    files, covering both diploid and polyploid species. NOTE: *The
    diploidization processing simplifies genotype data and does not
    account for allelic dosage effects.*

    For more information: [Data
    Input](https://teddyenn.github.io/ShiNyP-guide/sec-data-input.html)

3.  **What kind of output does the platform provide?**

    The platform generates customizable figures (PDF, PNG, or JPEG) and
    tables, reusable R data objects, and AI-assisted reports that
    summarize analytical results in natural language.

4.  **Can I analyze large SNP datasets with *ShiNyP*?**

    Yes, *ShiNyP* is optimized for both moderate and large-scale SNP
    datasets. However, performance may depend on your system’s hardware
    specifications.

5.  **Can *ShiNyP* export data to formats used by other genetics
    software?**

    Yes, results and transformed data can be exported in formats
    compatible with tools such as R, STRUCTURE, PLINK, GenAlEx, and
    others.

    For more information: [Data
    Transform](https://teddyenn.github.io/ShiNyP-guide/sec-data-conversion.html)

------------------------------------------------------------------------

## Support {.unnumbered}

1.  **Is *ShiNyP* open-source? Is it possible to extend *ShiNyP* with
    custom modules or scripts?**

    Yes, *ShiNyP* is released under an open-source license ([GNU Affero
    General Public
    License](https://www.gnu.org/licenses/agpl-3.0.html.en)). The source
    code is available on GitHub for transparency and community
    contributions.

2.  **Where can I report bugs or request new features?**

    If you encounter any issues or have suggestions for new features,
    please submit a request on the [GitHub Issues
    page](https://github.com/TeddYenn/ShiNyP/issues) or email us
    at: [teddyhuangyh\@gmail.com](#0){.email}. The project is actively
    maintained and welcomes community feedback and collaboration.

------------------------------------------------------------------------

## Instal**lation Issues** {.unnumbered}

> If you encounter any issues while installing *ShiNyP*, please don't
> hesitate to let us know. The issue may not be unique to you, and by
> reporting it, you help improve the entire community. Below are some
> common installation issues:

-   **R and Bioconductor version mismatch**

    The installation specifies Bioconductor version 3.21, which requires
    R version ≥ 4.5. If your R version is below 4.5, update it from
    [CRAN](https://cran.r-project.org/).

    ``` r
    # Check your R version 
    R.version.string
    ```

-   **Permission denied: curl.dll**

    Please close all R/RStudio programs and terminal windows to ensure
    no sessions are using the package, then restart and try installing
    again.

-   **Installation of dependencies**

    Installing packages like *shiny* and *dartR* may require additional
    developer tools. You might encounter error messages such as:

    ``` r
    ERROR: dependencies 'shiny', 'dartR' are not available for package 'ShiNyP'
    ```

    -   **For Windows**: Download Rtools from [**CRAN
        Rtools**](https://cran.r-project.org/bin/windows/Rtools/).

    -   **For macOS**: Open Terminal and run the installation command:

        ``` bash
        xcode-select --install
        ```

-   **GitHub installation issues**

    Verify that your system is connected to the internet. Check for any
    firewall or proxy settings that might block GitHub access.

-   **Package loading issues**

    Errors occur when loading *ShiNyP* or its dependencies, possibly due
    to outdated packages or conflicts. **Update all installed
    packages.**

------------------------------------------------------------------------

## Index {.unnumbered}

-   AI Report
    [8](https://teddyenn.github.io/ShiNyP-guide/sec-ai-report.html#sec-ai-report)
-   AMOVA (Analysis of MOlecular VAriance)
    [5.4](https://teddyenn.github.io/ShiNyP-guide/sec-genetic-diversity.html#amova-analysis-of-molecular-variance)
-   API key
    [8](https://teddyenn.github.io/ShiNyP-guide/sec-ai-report.html#step-2-ai-driven-report)
-   Bayesian Information Criterion (BIC)
    [4.2](https://teddyenn.github.io/ShiNyP-guide/sec-population-structure.html#step-2-dapc-analysis)
-   Chromosome Info.
    [2.3](https://teddyenn.github.io/ShiNyP-guide/sec-data-qc.html#snp-density)
    [5.2](https://teddyenn.github.io/ShiNyP-guide/sec-genetic-diversity.html#circos-plot)
    [6.3](https://teddyenn.github.io/ShiNyP-guide/sec-selection-sweep.html#ibs-identity-by-state)
    [6.4](https://teddyenn.github.io/ShiNyP-guide/sec-selection-sweep.html#manhattan-plot-plus)
    [7.2](https://teddyenn.github.io/ShiNyP-guide/sec-core-collection.html#core-snp-set)
-   Circos Plot
    [5.2](https://teddyenn.github.io/ShiNyP-guide/sec-genetic-diversity.html#circos-plot)
-   Core Sample Set
    [7.1](https://teddyenn.github.io/ShiNyP-guide/sec-core-collection.html#core-sample-set)
-   Core SNP Set
    [7.2](https://teddyenn.github.io/ShiNyP-guide/sec-core-collection.html#core-snp-set)
-   DAPC (Discriminant Analysis of Principal Components)
    [4.2](https://teddyenn.github.io/ShiNyP-guide/sec-population-structure.html#dapc-discriminant-analysis-of-principal-components)
-   data.frame
    [1.1](https://teddyenn.github.io/ShiNyP-guide/sec-data-input.html#step-2-transform-to-data.frame)
-   Demo Data
    [1.1](https://teddyenn.github.io/ShiNyP-guide/sec-data-input.html#step-1-input-your-vcf-file)
-   Diversity Parameter
    [5.1](https://teddyenn.github.io/ShiNyP-guide/sec-genetic-diversity.html#diversity-parameter)
-   Genetic Distance
    [5.3](https://teddyenn.github.io/ShiNyP-guide/sec-genetic-diversity.html#genetic-distance)
-   genind
    [3](https://teddyenn.github.io/ShiNyP-guide/sec-data-conversion.html#step-1-transform-data.frame-to-genind)
-   genlight
    [5](https://teddyenn.github.io/ShiNyP-guide/sec-data-conversion.html#step-2-transform-genind-to-genlight)
-   Group Info.
    [3](https://teddyenn.github.io/ShiNyP-guide/sec-data-conversion.html#step-1-transform-data.frame-to-genind)
    [4.5](https://teddyenn.github.io/ShiNyP-guide/sec-population-structure.html#kinship-analysis)
    [4.6](https://teddyenn.github.io/ShiNyP-guide/sec-population-structure.html#scatter-plot-plus)
    [5.1](https://teddyenn.github.io/ShiNyP-guide/sec-genetic-diversity.html#diversity-parameter)
    [6.2](https://teddyenn.github.io/ShiNyP-guide/sec-selection-sweep.html#outflank)
-   Hardy-Weinberg equilibrium (HWE)
    [2.2](https://teddyenn.github.io/ShiNyP-guide/sec-data-qc.html#snp-qc)
-   Heterozygosity rate
    [2.1](https://teddyenn.github.io/ShiNyP-guide/sec-data-qc.html#sample-qc)
-   IBS (Identity By State)
    [6.3](https://teddyenn.github.io/ShiNyP-guide/sec-selection-sweep.html#ibs-identity-by-state)
-   Kinship Analysis
    [4.5](https://teddyenn.github.io/ShiNyP-guide/sec-population-structure.html#kinship-analysis)
-   Manhattan Plot
    [6.4](https://teddyenn.github.io/ShiNyP-guide/sec-selection-sweep.html#manhattan-plot-plus)
-   Minor allele frequency (MAF)
    [2.2](https://teddyenn.github.io/ShiNyP-guide/sec-data-qc.html#snp-qc)
-   Missing rate
    [2.1](https://teddyenn.github.io/ShiNyP-guide/sec-data-qc.html#sample-qc)
-   NJ (Neighbor-Joining) Tree
    [4.4](https://teddyenn.github.io/ShiNyP-guide/sec-population-structure.html#nj-neighbor-joining-tree)
-   OutFLANK
    [6.2](https://teddyenn.github.io/ShiNyP-guide/sec-selection-sweep.html#outflank)
-   PCA (Principal Component Analysis)
    [4.1](https://teddyenn.github.io/ShiNyP-guide/sec-population-structure.html#pca-principal-component-analysis)
-   pcadapt
    [6.1](https://teddyenn.github.io/ShiNyP-guide/sec-selection-sweep.html#pcadapt)
-   Permutation Test
    [5.4](https://teddyenn.github.io/ShiNyP-guide/sec-genetic-diversity.html#step-2-run-permutation-test)
-   Sample QC
    [2.1](https://teddyenn.github.io/ShiNyP-guide/sec-data-qc.html#sample-qc)
-   Scatter Plot
    [4.6](https://teddyenn.github.io/ShiNyP-guide/sec-data-qc.html#sample-qc)
-   *ShiNyP*
    [ShiNyP](https://teddyenn.github.io/ShiNyP-guide/sec-shinyp.html#sec-shinyp)
-   Site Info.
    [1.1](https://teddyenn.github.io/ShiNyP-guide/sec-data-input.html#step-2-transform-to-data.frame)
    [2.1](https://teddyenn.github.io/ShiNyP-guide/sec-data-qc.html#sample-qc)
    [2.2](https://teddyenn.github.io/ShiNyP-guide/sec-data-qc.html#snp-qc)
    [2.3](https://teddyenn.github.io/ShiNyP-guide/sec-data-qc.html#snp-density)
    [5.1](https://teddyenn.github.io/ShiNyP-guide/sec-genetic-diversity.html#diversity-parameter)
    [6.1](https://teddyenn.github.io/ShiNyP-guide/sec-selection-sweep.html#pcadapt)
    [6.2](https://teddyenn.github.io/ShiNyP-guide/sec-selection-sweep.html#outflank)
    [6.3](https://teddyenn.github.io/ShiNyP-guide/sec-selection-sweep.html#ibs-identity-by-state)
    [7.2](https://teddyenn.github.io/ShiNyP-guide/sec-core-collection.html#core-snp-set)
-   SNP Density
    [2.3](https://teddyenn.github.io/ShiNyP-guide/sec-data-qc.html#snp-density)
-   SNP QC
    [2.2](https://teddyenn.github.io/ShiNyP-guide/sec-data-qc.html#snp-qc)
-   Tree Plot
    [4.7](https://teddyenn.github.io/ShiNyP-guide/sec-population-structure.html#tree-plot-plus)
-   UPGMA (Unweighted Pair Group Method with Arithmetic mean) Tree
    [4.3](https://teddyenn.github.io/ShiNyP-guide/sec-population-structure.html#upgma-unweighted-pair-group-method-with-arithmetic-mean-tree)
-   VCF
    [1.1](https://teddyenn.github.io/ShiNyP-guide/sec-data-input.html#vcf)

------------------------------------------------------------------------

## Bibliography {.unnumbered}